#pragma once

enum COLOR {
	BLACK = 0,
	RED = FOREGROUND_RED,
	GREEN = FOREGROUND_GREEN,
	BLUE = FOREGROUND_BLUE,
	WHITE = RED | GREEN | BLUE,
	YELLOW = RED | GREEN,
	PINK = RED | BLUE,
	TURQUOISE = GREEN | BLUE,

	LIGHTER = FOREGROUND_INTENSITY,

	BLACK_BG = 0,
	RED_BG = BACKGROUND_RED,
	GREEN_BG = BACKGROUND_GREEN,
	BLUE_BG = BACKGROUND_BLUE,
	WHITE_BG = RED_BG | GREEN_BG | BLUE_BG,
	YELLOW_BG = RED_BG | GREEN_BG,
	PINK_BG = RED_BG | BLUE_BG,
	TURQUOISE_BG = GREEN_BG | BLUE_BG,

	LIGHTER_BG = BACKGROUND_INTENSITY
};
enum STATE_COLOR {
	NORMAL_C = COLOR::WHITE | COLOR::BLACK_BG,
	INVALID_NUMBER_C = COLOR::RED | COLOR::YELLOW_BG,
	WRONG_ARGUMENTS_C = COLOR::WHITE | COLOR::RED_BG
};

const HANDLE console = GetStdHandle(STD_OUTPUT_HANDLE);